// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsD43ykI9n_8XTTmZ-XDb6LytJeOPirPg',
    appId: '1:1015115439268:web:7ae5a4f3e0610201941a31',
    messagingSenderId: '1015115439268',
    projectId: 'watch-hub-8d8e2',
    authDomain: 'watch-hub-8d8e2.firebaseapp.com',
    storageBucket: 'watch-hub-8d8e2.appspot.com',
    measurementId: 'G-8KFPT0HQ74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQpuCNMky4drGt6VDqIULKGHeYgyGsJM',
    appId: '1:1015115439268:android:3e98cb3cd8f82cea941a31',
    messagingSenderId: '1015115439268',
    projectId: 'watch-hub-8d8e2',
    storageBucket: 'watch-hub-8d8e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_fMIxFZrD_lcQCMiHGc_tdhLDidJ4yI',
    appId: '1:1015115439268:ios:4fddb8013a831676941a31',
    messagingSenderId: '1015115439268',
    projectId: 'watch-hub-8d8e2',
    storageBucket: 'watch-hub-8d8e2.appspot.com',
    iosBundleId: 'com.example.watchHub1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_fMIxFZrD_lcQCMiHGc_tdhLDidJ4yI',
    appId: '1:1015115439268:ios:4fddb8013a831676941a31',
    messagingSenderId: '1015115439268',
    projectId: 'watch-hub-8d8e2',
    storageBucket: 'watch-hub-8d8e2.appspot.com',
    iosBundleId: 'com.example.watchHub1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsD43ykI9n_8XTTmZ-XDb6LytJeOPirPg',
    appId: '1:1015115439268:web:d89a2dc63050569b941a31',
    messagingSenderId: '1015115439268',
    projectId: 'watch-hub-8d8e2',
    authDomain: 'watch-hub-8d8e2.firebaseapp.com',
    storageBucket: 'watch-hub-8d8e2.appspot.com',
    measurementId: 'G-C373F6WC2R',
  );
}
